const GET_ALL_ITEMS_REQUEST = 'GET_ALL_BUILDINGS_REQUEST'
const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS'
const GET_ALL_ITEMS_ERROR = 'GET_ALL_ITEMS_ERROR'

export default {
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_SUCCESS,
  GET_ALL_ITEMS_ERROR
}
